### ISSUE TITLE
why fork nextcloud-ogra?

### ISSUE THREAD

**Issue by PeterNerlich** [ubam/nextcloud#1]
Why was nextcloud-ogra forked? Are we planning to contribute to the original and/or make our own version?

If so, a goalset or statement on this would be nice.

**Comment by Acid-Override** [comment]
Was nextcloud-ogra a fork of Milan's NC webapp and do we need an entire repo for this or just the instructions?  The repo could be useful as a reference for webapps though.  Just curious how this came to be.

**Comment by MK1973** [comment]
I have forked not to contribute but to follow the developer as UT compatibility wit NC it essential an this may be the condition for such success. There for I started the NC tutorial. I think this Mateo app should be one of new core apps. Forking until it is finished we can see the latest status. The same we should do maybe with uMatriks, Telegram...

**Comment by PeterNerlich** [comment]
I don't think [forking](https://help.github.com/articles/fork-a-repo/) is what you are searching for. [Watching](https://help.github.com/articles/watching-and-unwatching-repositories/) may not really be your goal either (if you just want to track new commits and not every discussion), but try that one.

If you want to stay up to date on the most recent development, a fork will not help you. [Since a fork is supposed to be a copy for you to work on or play with without affecting the original project](https://help.github.com/articles/fork-a-repo/), it also silently grows out of sync with the original, you have to check and sync with the original manually.

I don't want to delete something against your will, but I don't see any need to keep the repository in our list. As long as you have personal interest in that, I'd advise you create a fork on your GitHub profile instead of that of this GitHub organization.

**Comment by PeterNerlich** [comment]
fork was deleted

**Comment by wayneoutthere** [comment]
yeah!  Fork!  Fork Off!  Fork it!  Fork it all, anyway!
